name: Seed Blog to Postgres

on:
  workflow_dispatch:

jobs:
  seed:
    name: Run blog seeding script
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'website-integration/ArrowheadSolution/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: website-integration/ArrowheadSolution

      - name: 'Preflight: tsx availability'
        run: npx tsx --version
        working-directory: website-integration/ArrowheadSolution

      - name: Verify env
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is not set. Add SUPABASE_DATABASE_URL as a GitHub Actions secret." >&2
            exit 1
          fi
          echo "DATABASE_URL is set (hidden)"
        working-directory: website-integration/ArrowheadSolution

      - name: 'Debug: resolve DB host (no secrets)'
        run: |
          node -e "const u=new URL(process.env.DATABASE_URL);console.log('host:',u.hostname);require('dns').lookup(u.hostname,{all:true},(e,a)=>{if(e){console.error(e);process.exit(1);}console.log('addresses:',a);});"
        working-directory: website-integration/ArrowheadSolution

      - name: 'Rewrite DATABASE_URL to IPv4 host'
        run: |
          node -e "(async()=>{try{const fs=require('fs');const dns=require('dns').promises;const u=new URL(process.env.DATABASE_URL);const a=await dns.lookup(u.hostname,{family:4});u.hostname=a.address;if(!u.searchParams.has('sslmode')){u.searchParams.set('sslmode','require');}const sanitized=u.toString().replace(/:[^:@\\/]+@/,'://****@');console.log('using IPv4 addr:',a.address);console.log('sslmode:',u.searchParams.get('sslmode'));console.log('new DATABASE_URL (sanitized):',sanitized);fs.appendFileSync(process.env.GITHUB_ENV,`\nDATABASE_URL=${u.toString()}\n`);}catch(e){console.error(e);process.exit(1);}})()"
        working-directory: website-integration/ArrowheadSolution

      - name: Seed blog into Postgres
        run: npx tsx scripts/seed-blog.mts
        env:
          NODE_ENV: production
          NODE_OPTIONS: --dns-result-order=ipv4first
          PGSSLMODE: require
        working-directory: website-integration/ArrowheadSolution
