name: Seed Blog to Postgres

on:
  workflow_dispatch:

jobs:
  seed:
    name: Run blog seeding script
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'website-integration/ArrowheadSolution/package-lock.json'

      - name: Install dependencies (including dev)
        run: npm ci --include=dev
        working-directory: website-integration/ArrowheadSolution

      - name: Verify env
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is not set. Add SUPABASE_DATABASE_URL as a GitHub Actions secret." >&2
            exit 1
          fi
          echo "DATABASE_URL is set (hidden)"
        working-directory: website-integration/ArrowheadSolution

      - name: Seed blog into Postgres
        run: npx tsx scripts/seed-blog.mts
        working-directory: website-integration/ArrowheadSolution
