name: Verify RLS via REST

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'website-integration/ArrowheadSolution/drizzle/migrations/0001_blog_posts_rls.sql'

concurrency:
  group: verify-rls-rest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify RLS behavior using REST
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: Production
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'website-integration/ArrowheadSolution/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: website-integration/ArrowheadSolution

      - name: Compute short SHA
        id: sha
        run: echo "short=$(echo $GITHUB_SHA | cut -c1-8)" >> "$GITHUB_OUTPUT"

      - name: Preflight secrets
        run: |
          for v in SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY SUPABASE_ANON_KEY; do
            if [ -z "${!v:-}" ]; then
              echo "$v is not set" >&2
              exit 1
            fi
          done
          echo "All required secrets present (values hidden)"
        working-directory: website-integration/ArrowheadSolution

      - name: Verify RLS via REST
        run: |
          node scripts/verify-rls-rest.mjs 2>&1 | tee verify-rls-rest.log
        working-directory: website-integration/ArrowheadSolution

      - name: Upload verification artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-rls-rest-${{ steps.sha.outputs.short }}
          path: |
            website-integration/ArrowheadSolution/verify-rls-rest.json
            website-integration/ArrowheadSolution/verify-rls-rest.log
          if-no-files-found: warn
          retention-days: 30

      - name: Job summary
        if: always()
        run: |
          node -e "const fs=require('fs'); const p='verify-rls-rest.json'; if(!fs.existsSync(p)){ console.log('No verify-rls-rest.json; skipping'); process.exit(0);} const r=JSON.parse(fs.readFileSync(p,'utf8')); const hdr=['# Verify RLS via REST','','Pass: '+r.pass,'Anon published count: '+(r.checks?.anonPublishedCount??'N/A'),'Anon drafts count: '+(r.checks?.anonDraftsCount??'N/A'),'Service drafts count: '+(r.checks?.serviceDraftsCount??'N/A'),'','Messages:',...(r.messages||[]).map(m=>'- '+m)].join('\n'); fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, hdr); console.log('Wrote summary');"
        working-directory: website-integration/ArrowheadSolution
